import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
'auth.signInButton': 'Sign In',
'auth.signUpButton': 'Sign Up',
'auth.resetPasswordButton': 'Send Password Reset',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Password',
'auth.nameFormField': 'Name',
'auth.signInErrorTitle': 'Sign In Error',
'auth.signInError': 'Login failed: email or password incorrect.',
'auth.resetPasswordLabelButton': 'Forgot password?',
'auth.signUpLabelButton': 'Create an Account',
'auth.signUpErrorTitle': 'Sign Up Failed.',
'auth.signUpError': 'There was a problem signing up.  Please try again later.',
'auth.signInLabelButton': 'Have an Account? Sign In.',
'auth.resetPasswordNoticeTitle': 'Password Reset Email Sent',
'auth.resetPasswordNotice': 'Check your email and follow the instructions to reset your password.',
'auth.resetPasswordFailed': 'Password Reset Email Failed',
'auth.signInonResetPasswordLabelButton': 'Sign In',
'auth.updateUser': 'Update Profile',
'auth.updateUserSuccessNoticeTitle': 'User Updated',
'auth.updateUserSuccessNotice': 'User information successfully updated.',
'auth.updateUserEmailInUse': 'That email address already has an account.',
'auth.updateUserFailNotice': 'Failed to update user',
'auth.enterPassword': 'Enter your password',
'auth.cancel': 'Cancel',
'auth.submit': 'Submit',
'auth.changePasswordLabelButton': 'Change Password',
'auth.resetPasswordTitle': 'Reset Password',
'auth.updateProfileTitle': 'Update Profile',
'auth.wrongPasswordNoticeTitle': 'Login Failed',
'auth.wrongPasswordNotice': 'The password does not match our records.',
'auth.unknownError': 'Unknown Error',
'settings.title': 'Settings',
'settings.language': 'Language',
'settings.theme': 'Theme',
'settings.signOut': 'Sign Out',
'settings.dark': 'Dark',
'settings.light': 'Light',
'settings.system': 'System',
'settings.updateProfile': 'Update Profile',
'home.title': 'Home',
'home.nameLabel': 'Name',
'home.uidLabel': 'UID',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin User',
'app.title': 'Flutter Starter Project',
'validator.email': 'Please enter a valid email address.',
'validator.password': 'Password must be at least 6 characters.',
'validator.name': 'Please enter a name.',
'validator.number': 'Please enter a number.',
'validator.notEmpty': 'This is a required field.',
'validator.amount': 'Please enter a number i.e. 250 - no dollar symbol and no cents',
},
'fr': {
'auth.signInButton': 'S\'identifier',
'auth.signUpButton': 'S\'inscrire',
'auth.resetPasswordButton': 'Envoyer la réinitialisation du mot de passe',
'auth.emailFormField': 'E-mail',
'auth.passwordFormField': 'Mot de passe',
'auth.nameFormField': 'Nom',
'auth.signInErrorTitle': 'Connectez-vous une erreur',
'auth.signInError': 'La connexion a échoué: e-mail ou mot de passe incorrect.',
'auth.resetPasswordLabelButton': 'mot de passe oublié?',
'auth.signUpLabelButton': 'Créer un compte',
'auth.signUpErrorTitle': 'L\'inscription a échoué.',
'auth.signUpError': 'Il y avait un problème d\'inscription. Veuillez réessayer plus tard.',
'auth.signInLabelButton': 'Avoir un compte? S\'identifier.',
'auth.resetPasswordNoticeTitle': 'Mot de passe Réinitialiser le courrier électronique envoyé',
'auth.resetPasswordNotice': 'Vérifiez votre email et suivez les instructions pour réinitialiser votre mot de passe.',
'auth.resetPasswordFailed': 'Mot de passe Reset Email a échoué',
'auth.signInonResetPasswordLabelButton': 'S\'identifier',
'auth.updateUser': 'Mettre à jour le profil',
'auth.updateUserSuccessNoticeTitle': 'Mise à jour de l\'utilisateur',
'auth.updateUserSuccessNotice': 'Informations utilisateur mises à jour avec succès.',
'auth.updateUserEmailInUse': 'Cette adresse électronique a déjà un compte.',
'auth.updateUserFailNotice': 'Échec de la mise à jour de l\'utilisateur',
'auth.enterPassword': 'Tapez votre mot de passe',
'auth.cancel': 'Annuler',
'auth.submit': 'Soumettre',
'auth.changePasswordLabelButton': 'Changer le mot de passe',
'auth.resetPasswordTitle': 'réinitialiser le mot de passe',
'auth.updateProfileTitle': 'Mettre à jour le profil',
'auth.wrongPasswordNoticeTitle': 'Échec de la connexion',
'auth.wrongPasswordNotice': 'Le mot de passe ne correspond pas à nos enregistrements.',
'auth.unknownError': 'Erreur inconnue',
'settings.title': 'Paramètres',
'settings.language': 'Langue',
'settings.theme': 'Thème',
'settings.signOut': 'Se déconnecter',
'settings.dark': 'Sombre',
'settings.light': 'Léger',
'settings.system': 'Système',
'settings.updateProfile': 'Mettre à jour le profil',
'home.title': 'Accueil',
'home.nameLabel': 'Nom',
'home.uidLabel': 'Uid',
'home.emailLabel': 'E-mail',
'home.adminUserLabel': 'Utilisateur admin',
'app.title': 'Projet de démarrage à flutter',
'validator.email': 'S\'il vous plaît, mettez une adresse email valide.',
'validator.password': 'Le mot de passe doit être au moins de 6 caractères.',
'validator.name': 'S\'il vous plaît entrer un nom.',
'validator.number': 'S\'il vous plaît entrer un numéro.',
'validator.notEmpty': 'Ceci est un champ obligatoire.',
'validator.amount': 'S\'il vous plaît entrer un numéro I.E. 250 - aucun symbole dollar et sans centimes',
},
'es': {
'auth.signInButton': 'Iniciar sesión',
'auth.signUpButton': 'Inscribirse',
'auth.resetPasswordButton': 'Enviar restablecimiento de contraseña',
'auth.emailFormField': 'Correo electrónico',
'auth.passwordFormField': 'Contraseña',
'auth.nameFormField': 'Nombre',
'auth.signInErrorTitle': 'Error',
'auth.signInError': 'Error de inicio de sesión: correo electrónico o contraseña incorrecta.',
'auth.resetPasswordLabelButton': '¿Se te olvidó tu contraseña?',
'auth.signUpLabelButton': 'Crea una cuenta',
'auth.signUpErrorTitle': 'Registro fallido.',
'auth.signUpError': 'Hubo un problema registrándolo. Por favor, inténtelo de nuevo más tarde.',
'auth.signInLabelButton': '¿Tener una cuenta? Iniciar sesión.',
'auth.resetPasswordNoticeTitle': 'Restablecimiento de contraseña Correo electrónico enviado',
'auth.resetPasswordNotice': 'Revise su correo electrónico y siga las instrucciones para restablecer su contraseña.',
'auth.resetPasswordFailed': 'Falló el correo electrónico de restablecimiento de la contraseña',
'auth.signInonResetPasswordLabelButton': 'Iniciar sesión',
'auth.updateUser': 'Actualización del perfil',
'auth.updateUserSuccessNoticeTitle': 'Usuario actualizado',
'auth.updateUserSuccessNotice': 'Información del usuario actualizada con éxito.',
'auth.updateUserEmailInUse': 'Esa dirección de correo electrónico ya tiene una cuenta.',
'auth.updateUserFailNotice': 'Error al actualizar el usuario',
'auth.enterPassword': 'Ingresa tu contraseña',
'auth.cancel': 'Cancelar',
'auth.submit': 'Enviar',
'auth.changePasswordLabelButton': 'Cambiar la contraseña',
'auth.resetPasswordTitle': 'Restablecer la contraseña',
'auth.updateProfileTitle': 'Actualización del perfil',
'auth.wrongPasswordNoticeTitle': 'Error de inicio de sesion',
'auth.wrongPasswordNotice': 'La contraseña no coincide con nuestros registros.',
'auth.unknownError': 'Error desconocido',
'settings.title': 'Ajustes',
'settings.language': 'Idioma',
'settings.theme': 'Tema',
'settings.signOut': 'Desconectar',
'settings.dark': 'Oscuro',
'settings.light': 'Luz',
'settings.system': 'Sistema',
'settings.updateProfile': 'Actualización del perfil',
'home.title': 'Hogar',
'home.nameLabel': 'Nombre',
'home.uidLabel': 'Uid',
'home.emailLabel': 'Correo electrónico',
'home.adminUserLabel': 'Administrador',
'app.title': 'Folleto Proyecto de inicio',
'validator.email': 'Por favor, introduce una dirección de correo electrónico válida.',
'validator.password': 'La contraseña debe tener al menos 6 caracteres.',
'validator.name': 'Por favor ingrese un nombre.',
'validator.number': 'Por favor, introduzca un número.',
'validator.notEmpty': 'Este es un campo obligatorio.',
'validator.amount': 'Por favor ingrese un número I.E. 250 - Sin símbolo de dólar y sin centavos',
},
'de': {
'auth.signInButton': 'Einloggen',
'auth.signUpButton': 'Anmeldung',
'auth.resetPasswordButton': 'Passwort zurücksetzen.',
'auth.emailFormField': 'Email',
'auth.passwordFormField': 'Passwort',
'auth.nameFormField': 'Name',
'auth.signInErrorTitle': 'Fehler anmelden',
'auth.signInError': 'Login fehlgeschlagen: E-Mail oder Passwort falsch.',
'auth.resetPasswordLabelButton': 'Passwort vergessen?',
'auth.signUpLabelButton': 'Ein Konto erstellen',
'auth.signUpErrorTitle': 'Anmeldung gescheitert.',
'auth.signUpError': 'Es gab ein Problem, das sich anmeldet. Bitte versuchen Sie es später erneut.',
'auth.signInLabelButton': 'Ein Konto haben? Einloggen.',
'auth.resetPasswordNoticeTitle': 'Passwort zurücksetzen E-Mail senden',
'auth.resetPasswordNotice': 'Überprüfen Sie Ihre E-Mail und befolgen Sie die Anweisungen, um Ihr Passwort zurückzusetzen.',
'auth.resetPasswordFailed': 'Passwort-Reset-E-Mail fehlgeschlagen',
'auth.signInonResetPasswordLabelButton': 'Einloggen',
'auth.updateUser': 'Profil aktualisieren',
'auth.updateUserSuccessNoticeTitle': 'Benutzeraktualisierung',
'auth.updateUserSuccessNotice': 'Benutzerinformationen erfolgreich aktualisiert.',
'auth.updateUserEmailInUse': 'Diese E-Mail-Adresse hat bereits ein Konto.',
'auth.updateUserFailNotice': 'Benutzer konnte nicht aktualisiert werden',
'auth.enterPassword': 'Geben Sie Ihr Passwort ein',
'auth.cancel': 'Abbrechen',
'auth.submit': 'einreichen',
'auth.changePasswordLabelButton': 'Passwort ändern',
'auth.resetPasswordTitle': 'Passwort zurücksetzen',
'auth.updateProfileTitle': 'Profil aktualisieren',
'auth.wrongPasswordNoticeTitle': 'Fehler bei der Anmeldung',
'auth.wrongPasswordNotice': 'Das Passwort entspricht nicht zu unseren Datensätzen.',
'auth.unknownError': 'Unbekannter Fehler',
'settings.title': 'Einstellungen',
'settings.language': 'Sprache',
'settings.theme': 'Thema',
'settings.signOut': 'Austragen',
'settings.dark': 'Dunkel',
'settings.light': 'Hell',
'settings.system': 'System',
'settings.updateProfile': 'Profil aktualisieren',
'home.title': 'Heim',
'home.nameLabel': 'Name',
'home.uidLabel': 'Uid',
'home.emailLabel': 'Email',
'home.adminUserLabel': 'Admin user.',
'app.title': 'Flattern-Starter-Projekt.',
'validator.email': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
'validator.password': 'Passwort muss mindestens 6 Zeichen lang sein.',
'validator.name': 'Bitte geben Sie einen Namen ein.',
'validator.number': 'Bitte gebe eine Nummer ein.',
'validator.notEmpty': 'Dies ist ein Pflichtfeld.',
'validator.amount': 'Bitte geben Sie eine Nummer ein, d. H. 250 - Kein Dollarsymbol und keine Cents',
},
'hi': {
'auth.signInButton': 'साइन इन करें',
'auth.signUpButton': 'साइन अप करें',
'auth.resetPasswordButton': 'पासवर्ड रीसेट भेजें',
'auth.emailFormField': 'ईमेल',
'auth.passwordFormField': 'पासवर्ड',
'auth.nameFormField': 'नाम',
'auth.signInErrorTitle': 'साइन इन त्रुटि',
'auth.signInError': 'लॉगिन विफल: ईमेल या पासवर्ड गलत है।',
'auth.resetPasswordLabelButton': 'पासवर्ड भूल गए?',
'auth.signUpLabelButton': 'खाता बनाएं',
'auth.signUpErrorTitle': 'साइन अप विफल रहा।',
'auth.signUpError': 'साइन अप करने में कोई समस्या थी। बाद में पुन: प्रयास करें।',
'auth.signInLabelButton': 'खाता होना? साइन इन करें।',
'auth.resetPasswordNoticeTitle': 'पासवर्ड रीसेट ईमेल भेजा गया',
'auth.resetPasswordNotice': 'अपना ईमेल जांचें और अपना पासवर्ड रीसेट करने के लिए निर्देशों का पालन करें।',
'auth.resetPasswordFailed': 'पासवर्ड रीसेट ईमेल विफल',
'auth.signInonResetPasswordLabelButton': 'साइन इन करें',
'auth.updateUser': 'प्रोफ़ाइल को नवीनतम बनाओ',
'auth.updateUserSuccessNoticeTitle': 'उपयोगकर्ता अपडेट किया गया',
'auth.updateUserSuccessNotice': 'उपयोगकर्ता की जानकारी सफलतापूर्वक अपडेट की गई।',
'auth.updateUserEmailInUse': 'उस ईमेल पते में पहले से ही एक खाता है।',
'auth.updateUserFailNotice': 'उपयोगकर्ता को अद्यतन करने में विफल',
'auth.enterPassword': 'अपना कूटशब्द भरें',
'auth.cancel': 'रद्द करें',
'auth.submit': 'प्रस्तुत करना',
'auth.changePasswordLabelButton': 'पासवर्ड बदलें',
'auth.resetPasswordTitle': 'पासवर्ड रीसेट',
'auth.updateProfileTitle': 'प्रोफ़ाइल को नवीनतम बनाओ',
'auth.wrongPasswordNoticeTitle': 'लॉगिन विफल',
'auth.wrongPasswordNotice': 'पासवर्ड हमारे रिकॉर्ड से मेल नहीं खाता है।',
'auth.unknownError': 'अज्ञात त्रुटि',
'settings.title': 'समायोजन',
'settings.language': 'भाषा',
'settings.theme': 'विषय',
'settings.signOut': 'साइन आउट',
'settings.dark': 'अंधेरा',
'settings.light': 'रोशनी',
'settings.system': 'प्रणाली',
'settings.updateProfile': 'प्रोफ़ाइल को नवीनतम बनाओ',
'home.title': 'घर',
'home.nameLabel': 'नाम',
'home.uidLabel': 'यूआईडी',
'home.emailLabel': 'ईमेल',
'home.adminUserLabel': 'व्यवस्थापक उपयोगकर्ता',
'app.title': 'फ्टरटर स्टार्टर परियोजना',
'validator.email': 'कृपया एक मान्य ईमेल पता प्रविष्ट करें।',
'validator.password': 'पासवर्ड कम से कम 6 अंकों का होना चाहिए।',
'validator.name': 'कृपया एक नाम दर्ज करें।',
'validator.number': 'एक संख्या दर्ज करें।',
'validator.notEmpty': 'यह एक अपेक्षित क्षेत्र है।',
'validator.amount': 'कृपया एक नंबर I.E 250 दर्ज करें - कोई डॉलर का प्रतीक और कोई सेंट नहीं',
},
'pt': {
'auth.signInButton': 'Entrar',
'auth.signUpButton': 'Inscrever-se',
'auth.resetPasswordButton': 'Enviar redefinição de senha',
'auth.emailFormField': 'O email',
'auth.passwordFormField': 'Senha',
'auth.nameFormField': 'Nome',
'auth.signInErrorTitle': 'Entre em erro',
'auth.signInError': 'Falha no login: Email ou senha incorreta.',
'auth.resetPasswordLabelButton': 'Esqueceu sua senha?',
'auth.signUpLabelButton': 'Crie a sua conta aqui',
'auth.signUpErrorTitle': 'Inscreva-se falhou.',
'auth.signUpError': 'Houve um problema em se inscrever. Por favor, tente novamente mais tarde.',
'auth.signInLabelButton': 'Ter uma conta? Entrar.',
'auth.resetPasswordNoticeTitle': 'Senha redefinir email enviado',
'auth.resetPasswordNotice': 'Verifique seu e-mail e siga as instruções para redefinir sua senha.',
'auth.resetPasswordFailed': 'Falha no email da redefinição de senha',
'auth.signInonResetPasswordLabelButton': 'Entrar',
'auth.updateUser': 'Atualizar perfil',
'auth.updateUserSuccessNoticeTitle': 'Usuário atualizado',
'auth.updateUserSuccessNotice': 'Informações do usuário atualizadas com êxito.',
'auth.updateUserEmailInUse': 'Esse endereço de e-mail já tem uma conta.',
'auth.updateUserFailNotice': 'Falha ao atualizar o usuário',
'auth.enterPassword': 'Coloque sua senha',
'auth.cancel': 'Cancelar',
'auth.submit': 'Enviar',
'auth.changePasswordLabelButton': 'Mudar senha',
'auth.resetPasswordTitle': 'Redefinir senha',
'auth.updateProfileTitle': 'Atualizar perfil',
'auth.wrongPasswordNoticeTitle': 'Falha no login',
'auth.wrongPasswordNotice': 'A senha não corresponde aos nossos registros.',
'auth.unknownError': 'Erro desconhecido',
'settings.title': 'Definições',
'settings.language': 'Língua',
'settings.theme': 'Tema',
'settings.signOut': 'Sair',
'settings.dark': 'Escuro',
'settings.light': 'Luz',
'settings.system': 'Sistema',
'settings.updateProfile': 'Atualizar perfil',
'home.title': 'Casa',
'home.nameLabel': 'Nome',
'home.uidLabel': 'Uid.',
'home.emailLabel': 'O email',
'home.adminUserLabel': 'Usuário de administrador.',
'app.title': 'Projeto de partida flutter.',
'validator.email': 'Por favor insira um endereço de e-mail válido.',
'validator.password': 'A senha deve ter pelo menos 6 caracteres.',
'validator.name': 'Por favor, insira um nome.',
'validator.number': 'Por favor, coloque um numero.',
'validator.notEmpty': 'Este é um campo obrigatório.',
'validator.amount': 'Por favor, insira um número I.E. 250 - Nenhum símbolo do dólar e sem centavos',
},
'zh': {
'auth.signInButton': '登入',
'auth.signUpButton': '报名',
'auth.resetPasswordButton': '发送密码重置',
'auth.emailFormField': '电子邮件',
'auth.passwordFormField': '密码',
'auth.nameFormField': '姓名',
'auth.signInErrorTitle': '签到错误',
'auth.signInError': '登录失败：电子邮件或密码不正确。',
'auth.resetPasswordLabelButton': '忘记密码？',
'auth.signUpLabelButton': '创建一个帐户',
'auth.signUpErrorTitle': '注册失败。',
'auth.signUpError': '注册了一个问题。请稍后再试。',
'auth.signInLabelButton': '有一个账户？登入。',
'auth.resetPasswordNoticeTitle': '密码重置电子邮件发送',
'auth.resetPasswordNotice': '检查您的电子邮件并按照说明重置密码。',
'auth.resetPasswordFailed': '密码重置电子邮件失败',
'auth.signInonResetPasswordLabelButton': '登入',
'auth.updateUser': '更新配置文件',
'auth.updateUserSuccessNoticeTitle': '用户更新',
'auth.updateUserSuccessNotice': '用户信息成功更新。',
'auth.updateUserEmailInUse': '该电子邮件地址已经有一个帐户。',
'auth.updateUserFailNotice': '无法更新用户',
'auth.enterPassword': '输入您的密码',
'auth.cancel': '取消',
'auth.submit': '提交',
'auth.changePasswordLabelButton': '更改密码',
'auth.resetPasswordTitle': '重设密码',
'auth.updateProfileTitle': '更新配置文件',
'auth.wrongPasswordNoticeTitle': '登录失败',
'auth.wrongPasswordNotice': '密码与我们的记录不匹配。',
'auth.unknownError': '未知错误',
'settings.title': '设置',
'settings.language': '语',
'settings.theme': '主题',
'settings.signOut': '登出',
'settings.dark': '黑暗的',
'settings.light': '光',
'settings.system': '系统',
'settings.updateProfile': '更新配置文件',
'home.title': '家',
'home.nameLabel': '姓名',
'home.uidLabel': 'uid',
'home.emailLabel': '电子邮件',
'home.adminUserLabel': '管理员用户',
'app.title': '扑腾启动项目',
'validator.email': '请输入有效的电子邮件地址。',
'validator.password': '密码必须至少6个字符。',
'validator.name': '请输入名称。',
'validator.number': '请输入一个数字。',
'validator.notEmpty': '这是一个必填字段。',
'validator.amount': '请输入一个号码i.e. 250  - 没有美元符号，没有美分',
},
'ja': {
'auth.signInButton': 'ログイン',
'auth.signUpButton': 'サインアップ',
'auth.resetPasswordButton': 'パスワードのリセットを送信します',
'auth.emailFormField': 'Eメール',
'auth.passwordFormField': 'パスワード',
'auth.nameFormField': '名前',
'auth.signInErrorTitle': 'エラー',
'auth.signInError': 'ログインに失敗しました：電子メールまたはパスワードが正しくありません。',
'auth.resetPasswordLabelButton': 'パスワードをお忘れですか？',
'auth.signUpLabelButton': 'アカウントを作成する',
'auth.signUpErrorTitle': 'サインアップに失敗しました。',
'auth.signUpError': 'サインアップが問題がありました。後でもう一度やり直してください。',
'auth.signInLabelButton': 'アカウントを持っています？ログイン。',
'auth.resetPasswordNoticeTitle': 'パスワードリセットメール送信',
'auth.resetPasswordNotice': '電子メールを確認して、指示に従ってパスワードをリセットしてください。',
'auth.resetPasswordFailed': 'パスワードリセットメールに失敗しました',
'auth.signInonResetPasswordLabelButton': 'ログイン',
'auth.updateUser': 'プロファイルを更新します',
'auth.updateUserSuccessNoticeTitle': 'ユーザーが更新されました',
'auth.updateUserSuccessNotice': 'ユーザー情報は正常に更新されました。',
'auth.updateUserEmailInUse': 'そのメールアドレスはすでにアカウントを持っています。',
'auth.updateUserFailNotice': 'ユーザーの更新に失敗しました',
'auth.enterPassword': 'パスワードを入力してください',
'auth.cancel': 'キャンセル',
'auth.submit': '送信',
'auth.changePasswordLabelButton': 'パスワードを変更する',
'auth.resetPasswordTitle': 'パスワードを再設定する',
'auth.updateProfileTitle': 'プロファイルを更新します',
'auth.wrongPasswordNoticeTitle': 'ログインに失敗しました',
'auth.wrongPasswordNotice': 'パスワードは私たちの記録と一致しません。',
'auth.unknownError': '未知のエラー',
'settings.title': '設定',
'settings.language': '言語',
'settings.theme': 'テーマ',
'settings.signOut': 'サインアウト',
'settings.dark': '暗い',
'settings.light': '光',
'settings.system': 'システム',
'settings.updateProfile': 'プロファイルを更新します',
'home.title': '家',
'home.nameLabel': '名前',
'home.uidLabel': 'UID.',
'home.emailLabel': 'Eメール',
'home.adminUserLabel': '管理ユーザー',
'app.title': 'フラッタースタータープロジェクト',
'validator.email': '有効なメールアドレスを入力してください。',
'validator.password': 'パスワードは少なくとも6文字でなければなりません。',
'validator.name': '名前を入力してください。',
'validator.number': '数字を入力してください。',
'validator.notEmpty': 'これは必要項目です。',
'validator.amount': '番号すなわち250  - ドル記号とセントなし',
},
'ru': {
'auth.signInButton': 'Войти',
'auth.signUpButton': 'Зарегистрироваться',
'auth.resetPasswordButton': 'Отправить пароль Сброс',
'auth.emailFormField': 'Эл. адрес',
'auth.passwordFormField': 'Пароль',
'auth.nameFormField': 'Имя',
'auth.signInErrorTitle': 'Войти по ошибке',
'auth.signInError': 'Не удалось в систему: электронная почта или пароль неверны.',
'auth.resetPasswordLabelButton': 'забыл пароль?',
'auth.signUpLabelButton': 'Завести аккаунт',
'auth.signUpErrorTitle': 'Регистрация прошла неудачно.',
'auth.signUpError': 'Была проблема подписания. Пожалуйста, попробуйте позже.',
'auth.signInLabelButton': 'Иметь аккаунт? Войти.',
'auth.resetPasswordNoticeTitle': 'Сброс пароля электронной почты отправлен',
'auth.resetPasswordNotice': 'Проверьте свою электронную почту и следуйте инструкциям для сброса пароля.',
'auth.resetPasswordFailed': 'Сброс пароля сброс электронной почты не удался',
'auth.signInonResetPasswordLabelButton': 'Войти',
'auth.updateUser': 'Обновить профиль',
'auth.updateUserSuccessNoticeTitle': 'Пользователь обновлен',
'auth.updateUserSuccessNotice': 'Информация о пользователе успешно обновляется.',
'auth.updateUserEmailInUse': 'Этот адрес электронной почты уже имеет учетную запись.',
'auth.updateUserFailNotice': 'Не удалось обновить пользователя',
'auth.enterPassword': 'Введите ваш пароль',
'auth.cancel': 'Отмена',
'auth.submit': 'Представлять на рассмотрение',
'auth.changePasswordLabelButton': 'Измени пароль',
'auth.resetPasswordTitle': 'Сброс пароля',
'auth.updateProfileTitle': 'Обновить профиль',
'auth.wrongPasswordNoticeTitle': 'Ошибка входа',
'auth.wrongPasswordNotice': 'Пароль не соответствует нашим записям.',
'auth.unknownError': 'Неизвестная ошибка',
'settings.title': 'Настройки',
'settings.language': 'Язык',
'settings.theme': 'Тема',
'settings.signOut': 'Выход',
'settings.dark': 'Темный',
'settings.light': 'Свет',
'settings.system': 'Система',
'settings.updateProfile': 'Обновить профиль',
'home.title': 'Дом',
'home.nameLabel': 'Имя',
'home.uidLabel': 'UID',
'home.emailLabel': 'Эл. адрес',
'home.adminUserLabel': 'Admin user.',
'app.title': 'Футтерс стартовый проект',
'validator.email': 'Пожалуйста, введите действительный адрес электронной почты.',
'validator.password': 'Пароль должен быть не менее 6 символов.',
'validator.name': 'Пожалуйста, введите имя.',
'validator.number': 'Пожалуйста, введите номер.',
'validator.notEmpty': 'Это обязательное поле.',
'validator.amount': 'Пожалуйста, введите номер I.E. 250 - Нет символа доллара и не центов',
},
        };
      }
      